### PR TITLE
creds: add environment variable support

### PR DESCRIPTION
**Pull request by snicol**

### CODE REVIEW

**Comment by snicol** [comment]
Sorry! This was destined for my own fork for a very niche (headless) use case. Closing this but happy to push upstream if this is something that could be useful.

**Comment by zierbeek** [comment]
You are using it headless? on a server?

**Comment by snicol** [comment]
Yep. I run f1viewer 24/7 on a server, using live triggers to start a [Restreamer](https://github.com/datarhei/restreamer) instance when a session goes live.

Allows me to access without need for VPN or using the F1 TV app’s awful AirPlay implementation!

**Comment by callumparr** [comment]
May you explain a little more. I am currently relying on VPN to access F1TV app from Japan. How do you get this to work without the need for VPN?

**Comment by snicol** [comment]
Sure!

I run f1viewer inside [`screen`](https://www.gnu.org/software/screen/) (tmux also works) on a server which has no IP/geo restrictions to F1TV, then using the [live session hooks](https://github.com/SoMuchForSubtlety/f1viewer/blob/master/README.md#live-session-hooks) it will call a bash script which starts a restreamer docker container with the f1viewer m3u8 URL (the one you’d usually put into VLC, mpv, etc) once an F1 sessions starts. When I access the proxied restreamer stream, it is without any restriction and I can use native players (e.g. Safari to AirPlay directly) - it is possible to use other methods like nginx reverse proxy instead of restreamer.

I don’t want to share too much of the setup and scripts because it would be very easy to make public or shared IPTV streams which isn’t my goal, this is purely for my own personal use whilst the app AirPlay functionality is in the state it’s in. I don’t want to be drawing too much attention to this project, encouraging piracy or the ability to stream in this way!

**Pull request closed without merging**
