### PR TITLE
Pass credentials as flags

### PR DESCRIPTION
**Pull request by jfoster**
Workaround for #74

### CODE REVIEW

**Comment by SoMuchForSubtlety** [comment]
Looks good, but the password will stay in the user's terminal history for an indeterminate amount of time. Maybe a better approach would be to start with a custom flag like `--login` and then prompting for email and password before starting the main program.

What do you think?

**Comment by jfoster** [comment]
That sounds like a good option if you don't like the idea of credentials being stored in the terminal history.
Would the login screen you have in mind just be as simple as prompting the user with `fmt.Println()` and reading back the credentials with `bufio.Scanner`?

**Comment by SoMuchForSubtlety** [comment]
Yes, that would do the trick.

**Comment by SoMuchForSubtlety** [comment]
superseded by https://github.com/SoMuchForSubtlety/f1viewer/pull/95

**Pull request closed without merging**
