### PR TITLE
add log out option

### PR DESCRIPTION
**Pull request by chrisvaughn**
Hey @SoMuchForSubtlety - 
This is a work in progress change for #70. If you have time I could use some direction on what to do after I clear out the credentials. So far, this change is effective in logging the current user out but I'm not sure the best way to "refresh" the UI with the logged-out state.  This seems like the work here would tie in nicely to #59 which I'm also up for working on.

Any direction you could provide would be appreciated.  Thanks for the great work you've done and thanks for letting other contribute.

### CODE REVIEW

**Comment by SoMuchForSubtlety** [comment]
The easy option would be to call `session.initUIWithForm()`. That would open the login form, but also reset the UI. As a first iteration that would be enough. 

The next step would be to leave the content selection tree in its current state and not reset it, but that will take some refactoring. I will probably to that when I implement #59

**Comment by chrisvaughn** [comment]
Thanks for the input.  I tried calling that right after session.logout() and I'm left with this where the logged in menu is there but just moved down.
f1viewer_and_f1viewer_–_main_go

Selecting a video and then "Play with MPV" results in a 401: Unauthorized as you'd expect. So if we are happy with this for a first iteration I'll submit the change. There's a bit of room for confusion but the bit login form above should give it away.

**Comment by SoMuchForSubtlety** [comment]
That looks correct, what do you mean by moved down? This is also how it looks when you first open the app, or when you open it without saved login credentials.

Additionally, I checked the code again, and I was wrong before, the content tree and "console output" don't get reset so nothing needs to be reloaded.

**Comment by chrisvaughn** [comment]
sorry for the confusion.  By "moved down" I was responding to when you said, "That would open the login form, but also reset the UI." I was trying to state that it didn't appear to reset the UI, it just pushed the existing UI down and put the form on top of it. Which sounds like that's what it's supposed to do.

So, It looks like we are all good with the basic behavior. Let me know if there's anything else I need to tweak with this.

**Comment by SoMuchForSubtlety** [comment]
The code looks good, but there are some formatting errors. Could you run it through gofmt? If you use vscode you can just right click and select "format document". 

Thanks!

**Comment by chrisvaughn** [comment]
Done. I didn't have my "on save" tools running for this repo.  Would you like me to squash the commits or is this good as is?

**Comment by SoMuchForSubtlety** [comment]
I can squash when I merge. Thanks for the contribution!

**Pull request merged**
