### PR TITLE
Add a favorites button

### PR DESCRIPTION
**Pull request by bviolier**
To start, thanks for making this!

Not sure if you are interested in this. I made it for myself, so if you are not interested, please close the PR :-) Note: nobody will notice this feature as long as they don't add anything to their config.

I wanted to have a way where I can easily load all the feeds that I want in a specific place. Because I am loading 7 feeds, I needed to make sure I loaded them all in the right place every time. With this configuration option, you can do that all automatically every time you want to watch a session.

PS. sorry for the whitespace changes.

### CODE REVIEW

**Comment by SoMuchForSubtlety** [comment]
Great idea!

Maybe instead of defining the commands in `favorites_playback_options` we could reference a `custom_playback_options` command title. That would make it simpler if all your favourites use the same command. What do you think?

**Comment by bviolier** [comment]
Sounds like a good idea! Will look at that. Do you think both should be possible (custom command AND reference) or just reference? I'm up for both.

**Comment by SoMuchForSubtlety** [comment]
Having both options sounds good.

**Comment by SoMuchForSubtlety** [comment]
I made an update, look over it and let me know what you think.

**Comment by bviolier** [comment]
Looks very good! Let's get it merged ;-)

**Pull request merged**
