### PR TITLE
removed v1-login to possibly fix #169

### LINKED ISSUE #169: could not authenticate in: got status 403
Cannot login. Some issue with the http requests and I am not sure what the issue is. To clarify I am on Windows 10 so this is not a complete duplicate of #167 as that user in on Mac.

403 error

### PR DESCRIPTION
**Pull request by Skinza**

### CODE REVIEW

**Comment by CAPSLOCK2000** [comment]
Works for me, I can watch races again! Tnx!

**Comment by LeJimster** [comment]
This appears to work for me too, I can login and play sessions.

**Comment by stephenbnicar** [comment]
This works for me on Pop! OS 20.10

**Comment by Kocicak** [comment]
I can also confirm that it works.

**Comment by Bubba14** [comment]
What part of the code did you remove for it to work?

**Comment by Robertsmania** [comment]
> How do I see if this fixes my issue? like how do I put into f1 viewer?

I'm a total n00b at this, but these are the steps I just took to verify it on my Windows10 system:

Get the source code.
Install the go language package from golang.org
Run the command as you have it in your source tree by going to f1viewer-master\f1viewer-master\cmd in a console window (powershell in windows) and executing it like so:
go run .
Try to login and verify that you see the error.
Navigate to your f1viewer-master\f1viewer-master\internal\ui folder and edit the state.go file as shown in the Files Changed tab
Effectively replace the old lines 164-168 with "err := s.v2.Authenticate(username, pw)"
Go back to your console window and re-run it from f1viewer-master\f1viewer-master\cmd:
go run .
Login again and see if your behavior is different.

**Comment by Bubba14** [comment]
> > How do I see if this fixes my issue? like how do I put into f1 viewer?
> 
> I'm a total n00b at this, but these are the steps I just took to verify it on my Windows10 system:
> 
> Get the source code.
> Install the go language package from golang.org
> Run the command as you have it in your source tree by going to f1viewer-master\f1viewer-master\cmd in a console window (powershell in windows) and executing it like so:
> go run .
> Try to login and verify that you see the error.
> Navigate to your f1viewer-master\f1viewer-master\internal\ui folder and edit the state.go file as shown in the Files Changed tab
> Effectively replace the old lines 164-168 with "err := s.v2.Authenticate(username, pw)"
> Go back to your console window and re-run it from f1viewer-master\f1viewer-master\cmd:
> go run .
> Login again and see if your behavior is different.

by any chance you know how to do this on mac?

**Comment by Bubba14** [comment]
> > How do I see if this fixes my issue? like how do I put into f1 viewer?
> 
> I'm a total n00b at this, but these are the steps I just took to verify it on my Windows10 system:
> 
> Get the source code.
> Install the go language package from golang.org
> Run the command as you have it in your source tree by going to f1viewer-master\f1viewer-master\cmd in a console window (powershell in windows) and executing it like so:
> go run .
> Try to login and verify that you see the error.
> Navigate to your f1viewer-master\f1viewer-master\internal\ui folder and edit the state.go file as shown in the Files Changed tab
> Effectively replace the old lines 164-168 with "err := s.v2.Authenticate(username, pw)"
> Go back to your console window and re-run it from f1viewer-master\f1viewer-master\cmd:
> go run .
> Login again and see if your behavior is different.

ok so I got it to work in a compiler but how do I save it as a application(or like it is when u download it off git hub

**Comment by Robertsmania** [comment]
> by any chance you know how to do this on mac?

Very little in those steps is platform specific.  On a mac you will need to open the Terminal application and change directories and stuff.  Here's what I just did...

Download the code for f1viewer by clicking the green Code button on this page and selecting download zip:
https://github.com/SoMuchForSubtlety/f1viewer
That probably put a f1viewer-master.zip file in your Downloads folder.

Download and install the Mac version of the go language from golang.org

Open the Terminal application.

On the console, execute these commands:
cd Downloads/
unzip f1viewer-master.zip 
cd f1viewer-master
cd cmd/
go run .

That should get some packages and maybe prompt you to install developer tools.  If it did need the developer tools, you may need to try running it again after they install.

You should get the f1viewer interface, try your login credentials and see if it works.
Use Control-C to quit.

Go to Downloads/f1viewer-master/internal/ui in your Finder.
Use some program (TextEdit?) to open state.go.
Modify it as shown in the Files Changed tab
Effectively replace the old lines 164-168 with "err := s.v2.Authenticate(username, pw)"
Save the state.go file.

Return to your Terminal window and re-run it:
go run .

The f1viewer interface should come up but now running with the modified code.
Try your credentials again and see if it works.

**Comment by Robertsmania** [comment]
> ok so I got it to work in a compiler but how do I save it as a application(or like it is when u download it off git hub

If all is well, build it into an application from that same cmd folder like so:
go build .

That will produce a "cmd" file that you can rename and move to wherever you like.

**Comment by Bubba14** [comment]
I can confirm this works

**Comment by slhodson969** [comment]
Steps to get this up and running on mac:

1. Open Terminal
2. Type and run `brew install go` (if you don't have Hombrew installed, see here https://brew.sh)
3. Download the code from https://github.com/Skinza/f1viewer (Green button > download zip)
4. In terminal type `cd ~/Downloads/f1viewer-master/cmd` (if your machine doesn't unzip the download, you may need to do it yourself first)
5. In terminal type and run `go build .`
6. After the go command finishes, type in terminal and run `./cmd`
7. You may be promoted to enter your keychain password. If so, enter your computer password.

You should now be up and running. At least this worked for me.

**Comment by jay-m-z** [comment]
> **Side note:** This was on an Intel MacBook Pro running macOS Big Sur 11.3.1. I'm not sure if it will work the same way on newer M1 Macs.

It works on M1 Air with macOS 11.4

**Comment by sluciow** [comment]
> 
> 
> > How do I see if this fixes my issue? like how do I put into f1 viewer?
> 
> I'm a total n00b at this, but these are the steps I just took to verify it on my Windows10 system:
> 
> Get the source code.
> Install the go language package from golang.org
> Run the command as you have it in your source tree by going to f1viewer-master\f1viewer-master\cmd in a console window (powershell in windows) and executing it like so:
> go run .
> Try to login and verify that you see the error.
> Navigate to your f1viewer-master\f1viewer-master\internal\ui folder and edit the state.go file as shown in the Files Changed tab
> Effectively replace the old lines 164-168 with "err := s.v2.Authenticate(username, pw)"
> Go back to your console window and re-run it from f1viewer-master\f1viewer-master\cmd:
> go run .
> Login again and see if your behavior is different.

So I am totally new to all this. Had it working prior to the issue (used Chocolatey). However, I am struggling to figure out step by step for the fix. Could you provide a play by play on how to get this up and running? Thanks in advance.

**Comment by Raineer** [comment]
> **Side note:** This was on an Intel MacBook Pro running macOS Big Sur 11.3.1. I'm not sure if it will work the same way on newer M1 Macs.

Confirmed 100% to work on 2020 M1 Mac Mini on macOS 11.4. Fixes both the (newer) 403 bug, but also the bug from the homebrew version where my F1 credentials never saved in the program. Thanks so so much!

**Comment by exit143** [comment]
> > by any chance you know how to do this on mac?
> 
> Very little in those steps is platform specific. On a mac you will need to open the Terminal application and change directories and stuff. Here's what I just did...
> 
>...................
>
> That will produce a "cmd" file that you can rename and move to wherever you like.

Dude. Thank you so much for such a perfect step by step. You're amazing!!!

**Pull request merged**
